Univirtual/my_card/card/urls.py
from django.urls import path
from . import views

app_name = 'card'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('student/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('teacher/', views.acerca, name='acerca')
]

Univirtual/my_card/my_card/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('card/', include('card.urls')),
]

Univirtual/my_card/card/models.py
from django.db import models
class Card(models.Model):
    # Campos del modelo
    name = models.CharField(max_length=30)
    excel_file = models.FileField(default='default_value', upload_to='uploads/')
 

    def __str__(self):
        return f"datos de la persona: {self.name}  {self.excel_file}"

Univirtual/my_card/card/views.py
from django.shortcuts import render, redirect
from . import models
from .models import Card

def list(request):
    all_cards = models.Card.objects.all()
    context = {'all_cards': all_cards}
    return render(request, 'card/list.html', context=context)

def add(request):
    if request.method == 'POST':
        name = request.POST['name']
        excel_file = request.POST['excel_file']
        
        new_card = Card(name=name, excel_file=excel_file)
        new_card.save()
        
        return redirect('card:list')
    else:
        return render(request, 'card/add.html')

def acerca(request):
    if request.method == 'POST':
        name = request.POST['name']
        excel_file = request.POST['excel_file']
        
        new_card = Card(name=name, excel_file=excel_file)
        new_card.save()
        
        return redirect('card:list')
    else:
        return render(request, 'card/acerca.html')

def delete(request):
    if request.method == 'POST':
        pk=request.POST['pk']
        try:
           models.Card.objects.get(pk=pk).delete()
           return render(request, 'card/delete.html')
        except:
            print("Error")
            return redirect('card:list')
    else:
        return render(request, 'card/delete.html')
    
def acerca(request):
    return render(request, 'card/acerca.html')

    

Univirtual/my_card/card/templates/card/acerca.html
{% extends "acerca.html" %}
{% load static %}
{% block content %}
<br>
<br>
<div class="container">
    <img class="rounded-image" src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="150" height="150">
    <p>
        <br>
        <br>
        Espacio para subir datos de los profesores.
    </p>
    <h1>Sube solo archivos tipo Excel</h1>
    <form action="" method='POST'>
    
        {% csrf_token %}

        <div class="form-group">
            <label for="name">Profesor:</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>

        <div class="form-group">
            <label for="excel_file">File:</label>
            <input type="file" class="form-control" id="excel_file" name="excel_file" placeholder="excel_file" required>
        </div>

        <div>
        <br>
        <input class="btn btn-primary" type="submit" value="Enviar"> 
        </div>
    </form>
</div>
{% endblock %}

Univirtual/my_card/card/templates/card/add.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<br>
<div class="container">
    <img class="rounded-image" src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="150" height="150">
    <p>
        <br>
        <br>
        Espacio para subir datos de los estudiantes.
    </p>
    <h1>Sube solo archivos tipo Excel</h1>
    <form action="" method='POST'>
    
        {% csrf_token %}

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>

        <div class="form-group">
            <label for="excel_file">File:</label>
            <input type="file" class="form-control" id="excel_file" name="excel_file" placeholder="excel_file" required>
        </div>

        <div>
        <br>
        <input class="btn btn-primary" type="submit" value="Enviar"> 
        </div>
    </form>
</div>
{% endblock %}

Univirtual/my_card/card/templates/card/delete.html
{% extends "base.html"%}
{% block content %}
<div class="container">
    <h1>Enter the primary key of the row you want to delete</h1>
    <div>
    <form action=" " method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">Primary Key: </label>
            <input class="form-control" type="text" name="pk" id="pk">
            <input class="form-control" type="submit" value = "Delete" >
        </div>
    </form>
</div>
{% endblock %}

#Esta vista por el momento esta inactiva pero si se requiere solo es activar un link con el nombre
#de eliminar.

Univirtual/my_card/card/templates/card/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <br>
    <br>
    <h1>Visitas</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Upluaded files</th>
            </tr>
        </thead>
        <tbody>
            {% for card in all_cards %}
            <tr>
                <td>{{ card.name }}</td>
                <td>{{ card.files }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Univirtual/my_card/templates/acerca.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Univirtual</title>
  <link rel="stylesheet" href="{% static 'my_app/acerca.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

</head>
<body class="my-custom-body">
  <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
    <div class="bg-dark p-4 static-container">
        <ul class="nav flex-column">
                
                <li class="nav-item">
                <br>
                    <a class="nav-link text-white" href="{%url 'card:acerca'%}">Acerca de mi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{%url 'card:add'%}">Mensaje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="https://github.com/juanpablogt" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white active" aria-current="page" href="{%url 'card:list'%}">Visitas</a>
            </li>
            </ul>
      </div>
    </div>
<nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'card:add'%}">Univirtual</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</nav>
    {%block content%}
    {%endblock%}

</body>
</html>

Univirtual/my_card/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Univirtual</title>
  <link rel="stylesheet" href="{% static 'my_app/add.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

</head>
<body class="my-custom-body">
  <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
    <div class="bg-dark p-4 static-container">
        <ul class="nav flex-column">
                
                <li class="nav-item">
                <br>
                    <a class="nav-link text-white" href="{%url 'card:acerca'%}">Acerca de mi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{%url 'card:add'%}">Mensaje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="https://github.com/juanpablogt" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white active" aria-current="page" href="{%url 'card:list'%}">Visitas</a>
            </li>
            </ul>
      </div>
    </div>
<nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'card:add'%}">Univirtual</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</nav>
    {%block content%}
    {%endblock%}

</body>
</html>